TARGET = fahr2Celsius fahr2Celsius2. fahr2Celsius3 literal score triangle

all : ${TARGET} 


fahr2Celsius: $@
fahr2Celsius2.:$@
fahr2Celsius3: $@
literal: $@
score: $@
triangle: $@

clean:
	rm -f ${TARGET} celsius2Fahr